-- Reference taxonomy: product categories.
-- Using INSERT OR IGNORE so this migration is idempotent on repeated runs.

INSERT OR IGNORE INTO product_categories (id, name, parent_id) VALUES
    (1,  'Beverages',       NULL),
    (2,  'Alcoholic',       1),
    (3,  'Non-Alcoholic',   1),
    (4,  'Beer',            2),
    (5,  'Wine',            2),
    (6,  'White Wine',      5),
    (7,  'Rosé Wine',       5),
    (8,  'Red Wine',        5),
    (9,  'Sparkling Wine',  5),
    (10, 'Spirits',         2),
    (11, 'Vodka',           10),
    (12, 'Gin',             10),
    (13, 'Rum',             10),
    (14, 'Tequila',         10),
    (15, 'Whiskey',         10),
    (16, 'Liqueur',         10),
    (17, 'Aperitif',        10),
    (18, 'Cachaça',         10),
    (19, 'Syrups & Purées', 1),
    (20, 'Syrups',          19),
    (21, 'Fruit Purées',    19),
    (22, 'Energy Drinks',   3),
    (23, 'Soft Drinks',     3),
    (24, 'Coffee & Hot Beverages', 3),
    (25, 'Dairy & Cheese',  NULL),
    (26, 'Oils & Vinegars', NULL),
    (27, 'Condiments & Preserves', NULL),
    (28, 'Spices & Herbs',  NULL),
    (29, 'Bakery & Confectionery', NULL),
    (30, 'Sugar & Sweeteners', NULL),
    (31, 'Savory Pies',     NULL),
    (32, 'Kitchen Supplies',NULL);
