from typing import Protocol


class CursorProtocol(Protocol):
    def execute(self, sql: str, params=None) -> "CursorProtocol": ...
    def fetchone(self) -> dict | None: ...
    def fetchall(self) -> list[dict]: ...
    @property
    def lastrowid(self) -> int | None: ...
    @property
    def rowcount(self) -> int: ...
    @property
    def connection(self) -> "DBConnection": ...


class DBConnection(Protocol):
    def execute(self, sql: str, params=None) -> CursorProtocol: ...
    def cursor(self) -> CursorProtocol: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
